// <auto-generated />
using System;
using Handball4RO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Handball4RO.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328180819_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Handball4RO.Models.Clasament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitieId")
                        .HasColumnType("int");

                    b.Property<int>("EchipaId")
                        .HasColumnType("int");

                    b.Property<int>("Egaluri")
                        .HasColumnType("int");

                    b.Property<int>("GoluriMarcate")
                        .HasColumnType("int");

                    b.Property<int>("GoluriPrimite")
                        .HasColumnType("int");

                    b.Property<int>("Infrangeri")
                        .HasColumnType("int");

                    b.Property<int>("MeciuriJucate")
                        .HasColumnType("int");

                    b.Property<int>("Puncte")
                        .HasColumnType("int");

                    b.Property<int>("Victorii")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetitieId");

                    b.HasIndex("EchipaId");

                    b.ToTable("Clasamente");
                });

            modelBuilder.Entity("Handball4RO.Models.Competitie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sezon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Competitii");
                });

            modelBuilder.Entity("Handball4RO.Models.Echipa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnInfiintare")
                        .HasColumnType("int");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Echipe");
                });

            modelBuilder.Entity("Handball4RO.Models.Jucator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EchipaId")
                        .HasColumnType("int");

                    b.Property<int?>("NumarTricou")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pozitie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EchipaId");

                    b.ToTable("Jucatori");
                });

            modelBuilder.Entity("Handball4RO.Models.Meci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataMeci")
                        .HasColumnType("datetime2");

                    b.Property<int>("EchipaGazdaId")
                        .HasColumnType("int");

                    b.Property<int>("EchipaOaspeteId")
                        .HasColumnType("int");

                    b.Property<int?>("ScorGazda")
                        .HasColumnType("int");

                    b.Property<int?>("ScorOaspete")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitieId");

                    b.HasIndex("EchipaGazdaId");

                    b.HasIndex("EchipaOaspeteId");

                    b.ToTable("Meciuri");
                });

            modelBuilder.Entity("Handball4RO.Models.Stire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AutorId")
                        .HasColumnType("int");

                    b.Property<string>("Continut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataPublicare")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagineUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Stiri");
                });

            modelBuilder.Entity("Handball4RO.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInregistrare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Handball4RO.Models.Clasament", b =>
                {
                    b.HasOne("Handball4RO.Models.Competitie", "Competitie")
                        .WithMany("Clasamente")
                        .HasForeignKey("CompetitieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Handball4RO.Models.Echipa", "Echipa")
                        .WithMany("Clasamente")
                        .HasForeignKey("EchipaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competitie");

                    b.Navigation("Echipa");
                });

            modelBuilder.Entity("Handball4RO.Models.Jucator", b =>
                {
                    b.HasOne("Handball4RO.Models.Echipa", "Echipa")
                        .WithMany("Jucatori")
                        .HasForeignKey("EchipaId");

                    b.Navigation("Echipa");
                });

            modelBuilder.Entity("Handball4RO.Models.Meci", b =>
                {
                    b.HasOne("Handball4RO.Models.Competitie", "Competitie")
                        .WithMany("Meciuri")
                        .HasForeignKey("CompetitieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Handball4RO.Models.Echipa", "EchipaGazda")
                        .WithMany("MeciuriAcasa")
                        .HasForeignKey("EchipaGazdaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Handball4RO.Models.Echipa", "EchipaOaspete")
                        .WithMany("MeciuriDeplasare")
                        .HasForeignKey("EchipaOaspeteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competitie");

                    b.Navigation("EchipaGazda");

                    b.Navigation("EchipaOaspete");
                });

            modelBuilder.Entity("Handball4RO.Models.Stire", b =>
                {
                    b.HasOne("Handball4RO.Models.User", "Autor")
                        .WithMany("Stiri")
                        .HasForeignKey("AutorId");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Handball4RO.Models.Competitie", b =>
                {
                    b.Navigation("Clasamente");

                    b.Navigation("Meciuri");
                });

            modelBuilder.Entity("Handball4RO.Models.Echipa", b =>
                {
                    b.Navigation("Clasamente");

                    b.Navigation("Jucatori");

                    b.Navigation("MeciuriAcasa");

                    b.Navigation("MeciuriDeplasare");
                });

            modelBuilder.Entity("Handball4RO.Models.User", b =>
                {
                    b.Navigation("Stiri");
                });
#pragma warning restore 612, 618
        }
    }
}
